name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Start CI Pipeline
    runs-on: ubuntu-latest
    steps:
      -  name: Checkout code
         uses: actions/checkout@v4
      
      -  name: Run docker compose
         uses: hoverkraft-tech/compose-action@v2.0.1
         with:
          compose-file: "./docker-compose.yml"

      #-  name: Run Super-Linter
      #   uses: github/super-linter@v4
      #   env:
      #     DEFAULT_BRANCH:  main
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
