name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Docker compose healt-check
    runs-on: ubuntu-latest
    steps:
      -  name: Checkout code
         uses: actions/checkout@v4
      
      -  name: Check service health
         uses: jaracogmbh/docker-compose-health-check-action@v1.0.0
         with:
          compose-file: "./docker-compose.yml"
          max-retries: 30
          retry-interval: 10
          skip-exited: "true"
          skip-no-healthcheck: "false"
         
