name: Docker images CI
on:
  push: 
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkoutt@v4
      - name: Build the docker-compose stack
      - run: docker-compose up -d
